name: nuwa_camera_streaming
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.8.15
  - pip=24.3.1
  - setuptools=75.3.0
  - wheel=0.45.1
  
  # Computer Vision & Image Processing
  - opencv=4.2.0
  - numpy=1.24.4
  
  # Development Tools
  - cmake=3.18.4
  
  # System Libraries (automatically handled by conda)
  - libgcc-ng=15.1.0
  - libstdcxx-ng=15.1.0
  - libgomp=15.1.0
  
  # Additional dependencies for camera streaming
  - ffmpeg=4.2.3
  - jpeg=9e
  - libpng=1.6.43
  - libtiff=4.4.0
  - zlib=1.2.13
    
# Environment variables (optional)
variables:
  # Set environment variables if needed
  # EXAMPLE_VAR: "value"
