name: nuwa_camera_streaming
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.8
  - pip
  - setuptools
  - wheel
  
  # Computer Vision & Image Processing (flexible versions for ARM64/Jetson compatibility)
  - numpy>=1.19,<2.0
  
  # Development Tools
  - cmake=3.18.4
  
  # System Libraries (automatically handled by conda)
  - libgcc-ng
  - libstdcxx-ng
  - libgomp
  
  # Additional dependencies for camera streaming
  - ffmpeg
  - jpeg
  - libpng
  - libtiff
  - zlib
  
  # Audio processing dependencies
  - pygame
  
  # Pip dependencies for packages not available in conda on ARM64
  - pip:
    - opencv-python>=4.2.0,<5.0.0
    - gtts>=2.4.0
    - pydub>=0.25.1
    
# Environment variables (optional)
variables:
  # Set environment variables if needed
  # EXAMPLE_VAR: "value"
